# Generated by Django 5.0.2 on 2024-04-07 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saved', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedevent',
            old_name='saved_at',
            new_name='saved_on',
        ),
        migrations.RenameField(
            model_name='savedproduct',
            old_name='saved_at',
            new_name='saved_on',
        ),
        migrations.RenameField(
            model_name='savedservice',
            old_name='saved_at',
            new_name='saved_on',
        ),
        migrations.RemoveField(
            model_name='savedproduct',
            name='item_type',
        ),
        migrations.AddField(
            model_name='savedevent',
            name='item_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedservice',
            name='item_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='savedevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='savedproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='savedservice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
